<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="192.168.1.4" failures="0" tests="12" name="tests.DashBoardTest.DashBoardTest" time="0.025" errors="3" timestamp="2025-01-11T10:36:33 IST" skipped="9">
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="logoutTest" time="0.000">
    <skipped/>
  </testcase> <!-- logoutTest -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="loginTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="DashBoardTestSam" time="0.000">
    <skipped/>
  </testcase> <!-- DashBoardTestSam -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="setWebDriver" time="0.008">
    <error message="Error at index 4 in: &quot;4444:4444&quot;" type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException: Error at index 4 in: "4444:4444"
at java.base/java.net.URL.<init>(URL.java:708)
at java.base/java.net.URL.<init>(URL.java:569)
at java.base/java.net.URL.<init>(URL.java:516)
at tests.AbstractTest.getRemoteDriver(AbstractTest.java:45)
at tests.AbstractTest.setWebDriver(AbstractTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:655)
at org.testng.TestRunner.beforeRun(TestRunner.java:644)
at org.testng.TestRunner.run(TestRunner.java:610)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: Error at index 4 in: "4444:4444"
at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83)
at java.base/java.lang.Integer.parseInt(Integer.java:751)
at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:237)
at java.base/java.net.URL.<init>(URL.java:703)
... 22 more
]]>
    </error>
  </testcase> <!-- setWebDriver -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="DashBoardTestSam" time="0.000">
    <skipped/>
  </testcase> <!-- DashBoardTestSam -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="logoutTest" time="0.000">
    <skipped/>
  </testcase> <!-- logoutTest -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="logoutTest" time="0.000">
    <skipped/>
  </testcase> <!-- logoutTest -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="setWebDriver" time="0.009">
    <error message="Error at index 4 in: &quot;4444:4444&quot;" type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException: Error at index 4 in: "4444:4444"
at java.base/java.net.URL.<init>(URL.java:708)
at java.base/java.net.URL.<init>(URL.java:569)
at java.base/java.net.URL.<init>(URL.java:516)
at tests.AbstractTest.getRemoteDriver(AbstractTest.java:45)
at tests.AbstractTest.setWebDriver(AbstractTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:655)
at org.testng.TestRunner.beforeRun(TestRunner.java:644)
at org.testng.TestRunner.run(TestRunner.java:610)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: Error at index 4 in: "4444:4444"
at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83)
at java.base/java.lang.Integer.parseInt(Integer.java:751)
at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:237)
at java.base/java.net.URL.<init>(URL.java:703)
... 22 more
]]>
    </error>
  </testcase> <!-- setWebDriver -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="loginTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="DashBoardTestSam" time="0.000">
    <skipped/>
  </testcase> <!-- DashBoardTestSam -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="loginTest" time="0.000">
    <skipped/>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.DashBoardTest.DashBoardTest" name="setWebDriver" time="0.008">
    <error message="Error at index 4 in: &quot;4444:4444&quot;" type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException: Error at index 4 in: "4444:4444"
at java.base/java.net.URL.<init>(URL.java:708)
at java.base/java.net.URL.<init>(URL.java:569)
at java.base/java.net.URL.<init>(URL.java:516)
at tests.AbstractTest.getRemoteDriver(AbstractTest.java:45)
at tests.AbstractTest.setWebDriver(AbstractTest.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:655)
at org.testng.TestRunner.beforeRun(TestRunner.java:644)
at org.testng.TestRunner.run(TestRunner.java:610)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NumberFormatException: Error at index 4 in: "4444:4444"
at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83)
at java.base/java.lang.Integer.parseInt(Integer.java:751)
at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:237)
at java.base/java.net.URL.<init>(URL.java:703)
... 22 more
]]>
    </error>
  </testcase> <!-- setWebDriver -->
</testsuite> <!-- tests.DashBoardTest.DashBoardTest -->
